### ISSUE TITLE
Bug: Assymetric AO limit kills players supposed to be outside of it

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#110]
Blufor has an AO soft limit, using the ao_limit_soft module:
`[blufor, "entireAO"] call FUNC(addAOMarker);`

Opfor has no restrictions, as they spawn way outside the AO, and have teleporters to move in at a later time.

On load all Opfor players get instakilled.

**Comment by EM-Creations** [comment]
Lol thanks for the bug report, I'll look into it, sounds fun.

**Comment by EM-Creations** [comment]
PR raised to fix this: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/113
