### ISSUE TITLE
Headless AI - Bunker - Strange friendly fire

### ISSUE THREAD

**Issue by TheLocalPub** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#112]
Video reference: https://www.youtube.com/watch?v=W0LsoxKAGyM&ab_channel=ThePubHuB

- Where: Single player
- What: Bunker AI after around 5 seconds, upon my first wave of enemy spawning in, all turn and engage me for a few moments before returning to normal.

**Comment by PiZZAD0X** [comment]
Please upload your mission so I can replicate this

**Comment by PiZZAD0X** [comment]
Tested mission a few times, cannot replicate the strange friendly fire at the start as in the video
