### ISSUE TITLE
Headless AI ignore waypoint completion radius

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#115]
Place AI, sync to headless. Assign a MOVE waypoint and set the completion radius to 100m.

It would be expected that once the AI arrives within 100 meters to the waypoint, it would consider it to be completed.

What actually happens, is that the AI still travel all the way to the center of the waypoint, regardless of any other setting, before considering it to be completed.

**Comment by PiZZAD0X** [comment]
Can replicate, working on it.

**Comment by PiZZAD0X** [comment]
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/commit/3d60d5edce05d61fa021772f497fe4b882a0cb26
