### ISSUE TITLE
Dev: Anti-ND can cook a weapon

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#116]
Using the updated FW, enabled anti-nd at start causes the weapon to have virtually infinite ammunition, requiring no reload from the player.
With the ACE weapon cookoff settings, you can easily overheat your weapon, which in turn will cause weapon cook-offs leading to a cascade overheat-cookoff loop until the weapon jams.

**Comment by PiZZAD0X** [comment]
should be fixed with the new Anti ND method now merged in the FW
