### ISSUE TITLE
Dev: Snow module doesn't have a setting to turn off snowing effect

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#117]
Current settings in the Snow module are the following:
```
GVAR(breath) = false;
GVAR(shiver) = true;
GVAR(postProcessing) = false;
GVAR(snowFog) = false;

//Fog Settings
GVAR(fog) = false;
GVAR(density) = 0.6; //Scale from 0-1
GVAR(decay) = 0;
GVAR(baseHeight) = 0;
```
No option to turn off snow. On winter maps, having no snow but shivering and breath yes, would be ideal.

**Comment by EM-Creations** [comment]
This is an enhancement, not a bug, it currently works as intended just FYI @goosko .

**Comment by PiZZAD0X** [comment]
Easy to do and yeah makes sense

**Comment by PiZZAD0X** [comment]
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/118/commits/ef1961ab6902bddc0124a9d8df5b6cbd504eb5b4
