### ISSUE TITLE
Anti-nd module: Can use turrets during anti-nd

### ISSUE THREAD

**Issue by TheLocalPub** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#143]
Environment: Dedicated MP
What happened: While anti-nd was on, I was able to enter a turret and fire.

Other: The Anti-nd doesn't seem to disabled after X time.

**Comment by EM-Creations** [comment]
Are you using the latest Anti ND version? I was testing it yesterday and the time setting was definitely working.

**Comment by PiZZAD0X** [comment]
@TheLocalPub please test using latest dev

**Comment by PiZZAD0X** [comment]
tested with last PR, does not allow vehicle/FFV firing
