### ISSUE TITLE
Firemission module not working for JIP FOs

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#154]
To reproduce:

1. Set up Firemission with player FO
2. Have a player JIP

JIPs do not have the ACE self-interact option to call in firemissions.

**Comment by PiZZAD0X** [comment]
Seems to be an issue with the JIP and the setobserver event. It can be changed to the global JIP event, or observer values could be set on the player object and the check for observer done on an initPost eventhandler @EM-Creations

**Comment by EM-Creations** [comment]
Not resolved.

**Comment by EM-Creations** [comment]
Going to close this for now as I played a mission using this at the weekend with no issue, if it recurrs / is an ongoing issue another issue can be raised.
