### ISSUE TITLE
Feature Request: Add a module for CTAB integration

### ISSUE THREAD

**Issue by NWhite421** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#155]
#### Feature Intent

CTAB has a function for defining vehicles with specific interactions with the mod, the likes of which are defined in [this link](https://github.com/Riouken/cTab/blob/master/userconfig/ctab/ctab_settings.hpp). Add either a default assumption or a module to define which vehicles can access the different levels of CTAB.

#### Screenshots

nil 

#### Possible Implementation

- Could be done in the custom init files, but the implication for adding custom vehicles would not serve the framework's purpose. A specific module would suffice. 
- Could be done with default init files, but in the event GC were to remove the mod, the entire framework would break and/or cause an issue. A module would be sufficient to check for such events.

#### Additional notes

Added on behalf of Reddish_Red and jubxxxjub.

**Comment by PiZZAD0X** [comment]
Could make a module that would not break if the mod was removed. Simply needs addon checks or null check on the functions/vars

**Comment by EM-Creations** [comment]
Working on this..
