### ISSUE TITLE
Loss of control over AI driver if another player gets into the commander seat

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#156]
Enable AI driver while in the gunner seat of a vehicle.
If a player gets in to the commander seat, the existing AI driver created by the gunner stops functioning.

The other issue is that players are able to get into the driver seat even if there is an AI driver already occupying it.

**Comment by PiZZAD0X** [comment]
I believe this has always been the case, has it not?

**Comment by goosko** [comment]
Yes. It has been a bane of missions where AI driver is enabled.

**Comment by PiZZAD0X** [comment]
I believe the commander switch may be possible, not sure about blocking the seat

**Comment by PiZZAD0X** [comment]
recent changes in this command may yield some success: https://community.bistudio.com/wiki/turretOwner
