### ISSUE TITLE
Respawn tickets counting from worng var

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#166]
Currently respawn tickets are set in the serverSettings.sqf by:
```
//Ticket pools for different sides
GVAR(RespawnTickets_West) = 0;
GVAR(RespawnTickets_East) = 21;
GVAR(RespawnTickets_Ind) = 0;
GVAR(RespawnTickets_Civ) = 0;

//Individual Tickets for different sides 
GVAR(IndividualRespawnTickets_West) = 0;
GVAR(IndividualRespawnTickets_East) = 3;
GVAR(IndividualRespawnTickets_Ind) = 0;
GVAR(IndividualRespawnTickets_Civ) = 0;
```
and the clientSettings.sqf:
`GVAR(RespawnTickets) = 0; //Initialize individual client respawn tickets to 0`
The latter overwrites the former, thus all sides have the same individual respawn tickets, regardless of the available ticket pools.
This means that opfor players will respawn the same number of times as blufor.

**Comment by PiZZAD0X** [comment]
Check the new PR. RespawnTickets is meant for individual respawn amounts regardless of team values. The individual team values are for restricting the number a player can respawn while using the team ticket respawn system. So you leave respawnTickets at 0 if you want to use team ticket settings.

**Comment by goosko** [comment]
#165 
Issue fixed.
The hint is the only thing missing, but otherwise it's good.
