### ISSUE TITLE
Anti-ND bug, FW Ver 23/2/22

### ISSUE THREAD

**Issue by ReddishRed** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#184]
Video:
https://streamable.com/ldshsi

Explanation:
Anti-ND is eating rounds on vics because it sets vehicle guns on safe, I know it's the anti-ND module as disabling it fixes this issue!

- Reddish

**Comment by EM-Creations** [comment]
This should now be fixed, please re-open if not on the latest version of the dev branch.
