### ISSUE TITLE
Round(s) module

### ISSUE THREAD

**Issue by TheLocalPub** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#194]
Is there a possibility that a module could be made that would allow for mission to have round(s), in the sense that when X conditions are met, it'll respawn all users, move to locations, and increase the round count. Once round count is achieved, X end condition is triggered.

**Comment by PiZZAD0X** [comment]
The way that ArmA stores info throughout the mission means this is simply more trouble than it is worth. All the issues we sometimes get with modules and the FW in general would be 10x more likely with trying to reset rounds. The only good way to reset is by reloading a mission which clears the cache, or to purpose build a FW which incorporates this behaviour into it, but it would be limited to say the least. Cephei wanted to do this years ago, it did not end up well.
