### ISSUE TITLE
HC - Vic gunner bunker breaks ai

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#195]
To repro:

1. Set up a vehicle with a gunner and a driver, the driver being the group leader, and sync it to HC
2. Add a few waypoints within 100m for the driver to follow.
3. In the gunner's init, paste [this, “bunker”, true] call PZAI_fnc_setInit;
4. Start mission and spawn the HC group.

This causes the vehicle to become unresponsive and will fail to follow the waypoints, staying on it's spawn position.

**Comment by EM-Creations** [comment]
HC issue, assigned to @PiZZAD0X .

**Comment by PiZZAD0X** [comment]
Not intended to have a vehicle bunker AI gunner, or any vehicle position unless the vehicle is stationary... groups cannot handle the differences in targeting/ai visibility unless they are deliberately split which could be something to do in the future related to vehicle gunners, driving, convoys, etc.
