### ISSUE TITLE
Respawns do not add towards casualty count since that BI update

### ISSUE THREAD

**Issue by ReddishRed** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#197]
Respawns don't add towards the max count of units on the casualty count causing missions that use respawns to end early

Example:

There is 0 out of 1 deaths, someone dies it should go to 1 of 2 because he respawns instead it goes to 1 of 1, thus ending the mission early.

**Comment by TheLocalPub** [comment]
Can confirm. 

Causes massive issues for mission makers this. 
I'd suggest this as a priority fix.

**Comment by EM-Creations** [comment]
This needs to be investigated by @PiZZAD0X . I looked at this some time ago and couldn't work out what the problem was.

**Comment by PiZZAD0X** [comment]
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/202
