### ISSUE TITLE
Jip issue with ACRE and Attachments

### ISSUE THREAD

**Issue by ReddishRed** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#198]
As seen on Borealis, when people JIP the call FW_fnc_ACRES_SetRadio; feature is called again

Also JIPs did not have attachments

**Comment by EM-Creations** [comment]
Please raise a separate issue for attachments as it is a separate issue.

I thought I saw a problem with ACRE:
- When a user either respawns (unless they're in spectator), or joins into the game `FW_fnc_ACRES_ClientInit` is run. However, from looking at this I'm pretty sure all the code in that function is safe and shouldn't affect anyone except the current unit.

It's worth double checking that the FW_fnc_ACRES_SetRadio isn't called elsewhere (directly in the settings file or via another script in the mission) as that may be causing an issue.

**Comment by PiZZAD0X** [comment]
Addressed in https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/commit/bdeb65aed99446af6d9a1aaf5fbe4657299991f0
