### ISSUE TITLE
Spectator screen never shows killer

### ISSUE THREAD

**Issue by EM-Creations** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#20]
This feature used to work but now whenever the user presses "K" in the spectator screen seemingly no matter what happened the killer information is never "known". I have already done some preliminary investigation into this and will continue to do so.

**Comment by EM-Creations** [comment]
This may not be broken as I saw it working on a mission earlier today :S

**Comment by PiZZAD0X** [comment]
I believe it has to do with the ace intercept of the hit and killed eventhandlers. The eventhandler doing tracking (the stuff that appears at the end of the mission) should be more consistent.

**Comment by EM-Creations** [comment]
> I believe it has to do with the ace intercept of the hit and killed eventhandlers. The eventhandler doing tracking (the stuff that appears at the end of the mission) should be more consistent. 

Have you got any suggestions as to what to look into? I remember this seemed to work consistently before Christmas. Are we aware of any ACE updates which may have affected this?

**Comment by EM-Creations** [comment]
Did a bit of research into this, I think the variables being looked at are only local to the server, we'd probably need to recode this to do it the same way ACEX does, at some point.

Reference: https://github.com/acemod/ACEX/blob/master/addons/killtracker/XEH_postInit.sqf

**Comment by EM-Creations** [comment]
Haven't seen this issue recently, so closing for now.
