### ISSUE TITLE
ai_tasks will hunt INDFOR even if the side is set to friendly

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#200]
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/blob/1c1715f0e4ed8f2b655a66999754256fa42ca6bf/modules/ai_tasks/functions/AITSK/fn_findTarget.sqf#L12

If the AI is INDFOR, ai_tasks will have AI squads target BLUFOR and OPFOR even if either of these sides is set to friendly in multiplayer options.

**Comment by EM-Creations** [comment]
Good spot, thanks for the report, should be fixed in this PR: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/201
