### ISSUE TITLE
JIP module addition

### ISSUE THREAD

**Issue by TheLocalPub** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#219]
Is there a possibility that the JIP module could have a "Do nothing" option.
So a user can join the server still with the JIP module turned on, but doesn't have the option to teleport or request transport.
Selecting deny simply puts the client straight into spectator, while mission makers (I've previously needed this and could still do with it for a mission) may not want to stop clients joining, allow them to TP, or make a pop up hint appear on peoples screens for transport.

An example of when this would be ideal is with teleporters at spawn that TP you to starting locations when selected by the users.
You may not want the new JIP to be able to TP to their squad as it could be the wrong place, wrong time, and immediately die or become wounded from combat which has happened before, and you may not want them to be able to request transport due to there being none and/or it's immersion breaking the pop up hint.

**Comment by PiZZAD0X** [comment]
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/216

**Comment by TheLocalPub** [comment]
Case closed :)
