### ISSUE TITLE
Capture zone: Multiple capzones don't seem to work

### ISSUE THREAD

**Issue by TheLocalPub** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#222]
In the setting.sqf file for the capture_zone module I had my code ordered like so.

`["rcap", [west, east], [9999, 10]] call FUNC(setCaptureZone);
["testcap", [west, east], [10, 9999]] call FUNC(setCaptureZone);`

The 2nd cap "testcap" was cap-able but not the first.
I flipped these lines of code and then rcap became cap-able.

**Comment by PiZZAD0X** [comment]
Please test https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/tree/feature/headlessAdditions now as these commits were added:

https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/commit/e88a1322c0652e303d39a3c4db0c4e588109645b
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/commit/c5b7b3f75e35602eeb46ff4269cabaeeeb60d5de
