### ISSUE TITLE
Firemission module rewrite

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#226]
The **Firemission module** should be rewritten in a similar fashion to Tin's **virtual_firemission** module, which allows anyone to call in a firemission if they switch to a predetermined radio channel.

**Comment by EM-Creations** [comment]
I think to do this we'd need to make another way of setting whether a player has the action menu to call in firemissions or not based on their selected frequency.
