### ISSUE TITLE
JIP module to use game time counter

### ISSUE THREAD

**Issue by TheLocalPub** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#237]
Currently JIP allows mission makers to either teleport the player to squad, request transports, or deny them access and put them in spectator.

What if there was an option to allow JIP on a team but for a certain amount of time after map screen brief?

One of the biggest problems in TVTs are when players JIP in an cause an unfair advantage, such as literally spawning behind players - which has happened before, but at the same time 9/10 cases you want to let your players be able to JIP.

What if OPFOR were defenders, but I knew it'd atleast take BLUFOR 10mins to travel within possibile contact distance, during that 10min of waiting before fighting starts, there could be a window to allow JIPs, before it then denies and access to OPFOR and pushes the joining player to Spectator.

This gives clients the ability to quickly connect and get in before they would possibly gain an unfair advantage.
Also if a player crashes right at mission start, that's it... they can't rejoin that team if JIP is selected to DENY, which is what happened last weekend on my mission with Thwart who go Arma'd.

**Comment by PiZZAD0X** [comment]
DENY will block Jips only after the denyTime setting time has been reached, sounds like you could have had Thwart respawn if the mission denyTime was set higher

**Comment by PiZZAD0X** [comment]
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/blob/b5a76fdde636cb9b02734fd9aa61f5b1306798e6/modules/jip/settings.hpp#L4

**Comment by TheLocalPub** [comment]
Oh my bad. Was under the impression this was the time they had to use their jip option.

Noted
