### ISSUE TITLE
Side selection for cover map

### ISSUE THREAD

**Issue by TheLocalPub** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#238]
Reddish suggested an idea where the cover map module can have side specific cover maps.

**Comment by PiZZAD0X** [comment]
You can already do this: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/blob/b5a76fdde636cb9b02734fd9aa61f5b1306798e6/modules/cover_map/settings.sqf#L5

But perhaps we can just have an array for side markers (but the function calling allows for the ability for different units/groups of even the same side to have separate maps)

**Comment by PiZZAD0X** [comment]
covered in #250
