### ISSUE TITLE
remove_map module exceptions broke

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#264]
Steps to repro:
- Enable remove_map module.
- Set up a gearscript.
- in the remove_map settings set up any role as exception for either map or compass

Expected results:
Roles established as exceptions keep their maps and compasses after briefing.

Actual results:
Every role has their maps and compasses removed after briefing regardless of settings.

**Comment by PiZZAD0X** [comment]
fixed in #268
