### ISSUE TITLE
Vehicle gear script issue

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#29]
Using vanilla dev:

`[this, "HUMMVEE"] call FW_fnc_VehicleGearScript;`
The above script, when placed in the init of a vehicle, does nothing. My rpt has no reference to this issue.

**Comment by PiZZAD0X** [comment]
function was incorrectly named, try `[this, "HUMMVEE"] call FW_fnc_VehGear;`

**Comment by EM-Creations** [comment]
I can confirm that in the latest dev branch of the framework this appears to be working correctly using the correct way to call the vehicle gear script `[this, "HUMMVEE"] call FW_fnc_VehGearScript;`

![Test evidence](https://user-images.githubusercontent.com/8123733/114069103-86433580-9896-11eb-9ee5-955fec81cf2a.png)
