### ISSUE TITLE
Gear script issues

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#30]
The loadouts.sqf is empty. Using default gear scripts from the loadouts folder causes item overflow since the RemoveAllGear function is not called anywhere.

loadouts.sqf should include the following:
```
_unit call FW_fnc_RemoveAllGear;

//Insert your loadouts below.
#include "loadouts\1989VDV.sqf"
#include "loadouts\2000MSV.sqf"
#include "loadouts\BAF.sqf"
#include "loadouts\RURiflePlatoon.sqf"
#include "loadouts\USMCRiflePlatoon.sqf"
```

**Comment by PiZZAD0X** [comment]
RemoveAllGear included in gearscript with: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/31
loadouts.sqf should include some base loadout classes so it's easier to understand.

**Comment by EM-Creations** [comment]
Confirming that this is a persisting bug, I am fixing it now.

**Comment by EM-Creations** [comment]
PR raised to fix this.
