### ISSUE TITLE
Wrong params in the call_mission module

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#34]
17:07:27   Error position: <params [
["_callID", "", [""]],
["_callS>
17:07:27   Error Params: Type String, expected Array
17:07:27 File \modules\call_mission\init.sqf, line 131

To reproduce, enable the call_mission module and start any mission.

**Comment by EM-Creations** [comment]
The call_mission module has yet to be ported. Making as invalid for now. Please raise again if there's still an issue after its ported.
