### ISSUE TITLE
The AI_drivers module doesn't work

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#37]
To reproduce:
Place unit, place any tank, enable ai_drivers module, specify either var name, class name, or all tanks in the settings.

None of the above settings work. Couldn't find any reference to this issue in the rpt with debug on.

**Comment by EM-Creations** [comment]
Confirmed that this is a bug, fixing it now. Thank you @goosko

**Comment by EM-Creations** [comment]
PR raised for fix: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/46
