### ISSUE TITLE
Dev: HC sync error message

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#39]
Using the latest version of the dev, in local SP and MP, with HC enabled gives the following error every frame:

10:17:35 [FW] (PZAI) LOG: Executed spawnarray _Array: egy
10:17:35 [FW] (PZAI) LOG: !isMultiplayer createZone function executed
10:17:35 [FW] (PZAI) LOG: SpawnArray _Array: egy _initial: false
10:17:35 [FW] (PZAI) LOG: SpawnArray _Array: egy _entities: <null>
10:17:35 [FW] (PZAI) LOG: Getting Array data for egy
10:17:35 [FW] (PZAI) LOG: synced count for egy: 4
10:17:35 Error in expression <ities, 0, []] call PZAI_fnc_getDetails) select 1);
format ['[%1] (%2) %3: %4', t>
10:17:35   Error position: <select 1);
format ['[%1] (%2) %3: %4', t>
10:17:35   Error Zero divisor
10:17:35 File \modules\headless_ai\cfgXEH\init\GlobalPreInit.sqf..., line 56
10:17:35 Error in expression <

params ["_logic"];
private _synced = synchronizedObjects _logic;

{
private _>
10:17:35   Error position: <synchronizedObjects _logic;

{
private _>
10:17:35   Error synchronizedobjects: Type Array, expected Object
10:17:35 File modules\headless_ai\cfgFunctions\GetInfo\fn_getSynced.sqf [PZAI_fnc_getSynced]..., line 1997

Another byproduct, as tested with more than one logics, was that all AI units were spawned in, even the ones not called in the GVAR(InitialSpawn).

**Comment by EM-Creations** [comment]
Is this still an issue @goosko ?

**Comment by PiZZAD0X** [comment]
This was an error when the arrays didn't match in order or names, it shouldnt be an issue now.
