### ISSUE TITLE
Dev:  auto_track_assets error

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#40]
Using the latest dev, the auto_track_assets module raises the following issue:
I placed a vehicle without crew, then moved units spawned separately in. Headless was enabled on these units.

10:23:27   Error Undefined variable in expression: fnc_trackasset
10:23:27 File modules\auto_track_assets\init.sqf..., line 62
10:23:27 Error in expression <fg >> "displayName"), _x select 0] call FNC_TrackAsset;

};

};

} forEach FW_Te>

**Comment by PiZZAD0X** [comment]
The auto track assets module is no longer required as all created entities in runtime get tracked by default, will remove the references and module to dev
