### ISSUE TITLE
HC: fn_SearchBuilding debug markers

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#44]
The fn_SearchBuilding function creates debug markers even if they are disabled in the headless settings.

**Comment by goosko** [comment]
Adding a _bDebugMarker setMarkerAlpha 0; should fix it.

**Comment by PiZZAD0X** [comment]
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/38/commits/17e025856cdce168cb8b5959a41e1815294e10a4

**Comment by EM-Creations** [comment]
Good spot @goosko

**Comment by EM-Creations** [comment]
> [17e0258](https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/commit/17e025856cdce168cb8b5959a41e1815294e10a4)

Are you saying this should have been fixed since November?

**Comment by PiZZAD0X** [comment]
should be fixed with that commit
