### ISSUE TITLE
Bug: Firemission module AI observer

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#67]
Firemission module raised several error messages while trying to use AI observer. Tested with several different types of artillery.

Steps to recreate:

1. Place artillery (named grad_1), crew and observer units, all AI, all synced to HC.
2. Artillery init: `[this, "init", {[_this,200,300,300,11,12,"Grad 1",true] call FNC_SetArtilleryData;}] call PZAI_fnc_setInit;`
3. Observer init: `[this, "init", {[_this,[grad_1,grad_2],0.5,10,2000,100,5,10,180,150,0] call FNC_RegisterForwardObserver; 
	[_this,10,0] call FNC_SetObserverSkill;
	}] call PZAI_fnc_setInit;`

Expected outcome: The AI automatically call in firemissions on observed enemies.

Error messages:
1.
> modules\firemission\Dia\Dia_Global.sqf..., line 190
> 22:16:35 Error in expression <nes");
> {
> _ret pushBack [_x,0];
> }forEach _possibleMags;
> 
> {
> _check = _x;
> _found = >
> 22:16:35   Error position: <_possibleMags;
> 
> {
> _check = _x;
> _found = >
> 22:16:35   Error Undefined variable in expression: _possiblemags

2.
> modules\firemission\init.sqf..., line 343
> 22:16:37 Error in expression <s" / (_weaps select 0) / "reloadTime");
> _reloadTime
> };
> FNC_StopArtilleryClient =>
> 22:16:37   Error position: <_reloadTime
> };
> FNC_StopArtilleryClient =>
> 22:16:37   Error Undefined variable in expression: _reloadtime

3.
> modules\firemission\init.sqf..., line 867
> 22:16:37 Error in expression <nes");
> {
> _ret pushBack [_x,0];
> }forEach _possibleMags;
> 
> {
> _check = _x;
> _found = >
> 22:16:37   Error position: <_possibleMags;
> 
> {
> _check = _x;
> _found = >
> 22:16:37   Error Undefined variable in expression: _possiblemags

4.
> modules\firemission\init.sqf..., line 233
> 22:16:37 Error in expression <emissionRoundsRequired;
> 
> [_unit,_target,_roundClassName ] call FNC_InternalSpott>
> 22:16:37   Error position: <_roundClassName ] call FNC_InternalSpott>
> 22:16:37   Error Undefined variable in expression: _roundclassname

5.
> modules\firemission\init.sqf..., line 339
> 22:16:38 [HC] (PZAI) LOG: group invalid removing from array: B Alpha 2-2
> 22:16:41 Error in expression <ate _ret = _unit getArtilleryETA [_pos, _ammo];
> _ret
> };
> FNC_SetArtyFiremissionRo>
> 22:16:41   Error position: <_ammo];
> _ret
> };
> FNC_SetArtyFiremissionRo>
> 22:16:41   Error Undefined variable in expression: _ammo

6.
> modules\firemission\Dia\Dia_Global.sqf..., line 106
> 22:16:41 Error in expression <ce2D _target;
> _eta = [_unit,_randomPos, _roundClassName] call FNC_GetArtyEta;
> _u>
> 22:16:41   Error position: <_roundClassName] call FNC_GetArtyEta;
> _u>
> 22:16:41   Error Undefined variable in expression: _roundclassname

7.
> modules\firemission\init.sqf..., line 263
> 22:16:42 Error in expression <nes");
> {
> _ret pushBack [_x,0];
> }forEach _possibleMags;
> 
> {
> _check = _x;
> _found = >
> 22:16:42   Error position: <_possibleMags;
> 
> {
> _check = _x;
> _found = >
> 22:16:42   Error Undefined variable in expression: _possiblemags

**Comment by EM-Creations** [comment]
This module has just had a pull request raised to port it in the new version of the framework and should be available for testing shortly.
