### ISSUE TITLE
Bug: HC group unable to mount vehicles of other groups

### ISSUE THREAD

**Issue by goosko** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#90]
Steps to repro:

1. Create a manned vehicle/transport/aircraft, synced to HC.
2. Create a separate second AI group, synced to HC (can be the same logic as the first group).
3. Assign the second AI group via waypoint to GET IN the vehicle of the first group.

Expected outcome:
The second group mount up in the vehicle of the first group.

Actual outcome:
The second group ignores the vehicle and is unable to mount up.

The only way to have two different groups of HC AI in the same vehicle is to have the vehicle unmanned in the beginning, however this means that the vehicle cannot be synced to the HC.

**Comment by EM-Creations** [comment]
Is this a problem in the old framework or new (dev) framework or both?

**Comment by goosko** [comment]
Yes, this has been a persistent issue, even in the previous version.

**Comment by EM-Creations** [comment]
Assigned to @PiZZAD0X as it's related to HC.
