### ISSUE TITLE
Convert script based in game brief to module

### ISSUE THREAD

**Issue by TheLocalPub** [Global-Conflicts-ArmA/Olsen-Framework-Arma-3#95]
Take the in-game briefing/start script and convert it into a module.

**Comment by EM-Creations** [comment]
This will only be implemented for the new framework, I won't be supporting this in the old framework too.

**Comment by EM-Creations** [comment]
Done: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/98
